### ISSUE TITLE
Chrome

### ISSUE THREAD

**Issue by nekszer** [jxnblk/plangular#81]
Failed to execute 'open' on 'XMLHttpRequest': Refused to connect to 'https://api.soundcloud.com/resolve.json?url=http%3A%2F%2Fsoundcloud.com%2Fsaurom%2Ftracks&client_id=80fd133f50bab22c533510fbef3ae98a' because it violates the document's Content Security Policy.

at Error (native)
at corslite (file:///android_asset/www/scripts/plangular.js:328:7)
at module.exports (file:///android_asset/www/scripts/plangular.js:110:3)
at link (file:///android_asset/www/scripts/plangular.js:466:9)
at $ (file:///android_asset/www/scripts/angular.min.js:73:46)
at L (file:///android_asset/www/scripts/angular.min.js:61:495)
at g (file:///android_asset/www/scripts/angular.min.js:54:326)
at g (file:///android_asset/www/scripts/angular.min.js:54:349)
at g (file:///android_asset/www/scripts/angular.min.js:54:349)
at g (file:///android_asset/www/scripts/angular.min.js:54:349)
<div plangular='http://soundcloud.com/saurom/tracks'>

Using Chrome in Mozilla Works Fine and Opera Works Fine...

**Comment by jxnblk** [comment]
Could you please clarify this issue.

**Comment by nekszer** [comment]
i can solve, the problem was declaration of angular module
